project_id = "qpljdthnqdatcirkudpc"

[functions.sitemap]
verify_jwt = false

[functions.create-article]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.send-email]
verify_jwt = false
