project_id = "qpljdthnqdatcirkudpc"

[functions.sitemap]
verify_jwt = false

[functions.create-article]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-newsletter]
verify_jwt = false

[functions.unsubscribe-newsletter]
verify_jwt = false

[functions.manage-user]
verify_jwt = false